export const SIGNUP_SUCCESS = 'SIGNUP_SUCCES';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCES';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';