# Generated by Django 4.1 on 2022-09-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_date_created_product_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/'),
        ),
    ]
